### ISSUE TITLE
插件使用问题

### ISSUE THREAD

**Issue by XIAOGUIGUI** [easy-team/egg-view-vue-ssr#12]
这个egg插件是不是只能使用在你构建的框架基础上开发？使用官网的vue-hackernews-2.0示例是无法运行起来的

**Comment by hubcarl** [comment]
可以的，不过有有个约束，需要 config/manifest.json

**Comment by hubcarl** [comment]
@XIAOGUIGUI 最新的 manifest.json 非必须
