### ISSUE TITLE
如何添加scss支持

### ISSUE THREAD

**Issue by ITHcc** [easy-team/egg-view-vue-ssr#13]
我已在webpack.config.js的module中添加了scss的相关规则 但是编译时会报错

`ERROR in ./app/web/page/login/login.vue?vue&type=style&index=0&id=160ccdda&rel=stylesheet%2Fscss&lang=scss&scoped=true& (./node_modules/vue-loader/lib??vue-loader-options!./app/web/page/login/login.vue?vue&type=style&index=0&id=160ccdda&rel=stylesheet%2Fscss&lang=scss&scoped=true&) 129:0
Module parse failed: Unexpected token (129:0)
You may need an appropriate loader to handle this file type`

**Comment by ITHcc** [comment]
> module: {
    rules:[
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader',
          'postcss-loader'
        ],
        exclude: /node_modules/
      },
      {
        test: /\.scss$/,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader'
        ]
      },
      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        options: {
          symbolId: 'icon-[name]'
        }
      },
    ]
  },

**Comment by ITHcc** [comment]
~~~javascript
module: {
    rules:[
      { scss: true }
    ]
  },
~~~
根据easywebpack官网改成这样后还是不行


~~~javascript
ERROR in ./app/web/page/login/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
~~~

**Comment by hubcarl** [comment]
![image](https://user-images.githubusercontent.com/4983042/65845331-6f9c5400-e36c-11e9-912c-55ce9c19e761.png)

请问是否按照这个配置了？
