### ISSUE TITLE
请问如何做才能拿到渲染好之后的html

### ISSUE THREAD

**Issue by shenjianzch** [easy-team/egg-view-vue-ssr#7]
![image](https://user-images.githubusercontent.com/7286498/41815459-3d016610-779e-11e8-9359-65b62a6bd92b.png)
比如是这样的 拿到的是前端的模板 数据是没有的 有没那种方法可以拿到渲染完之后的html 因为我想再egg 上转成pdf 然后扔给前端 用来打印用 类似 还是必须要用到像ejs 这样的模板引擎

**Comment by hubcarl** [comment]
@shenjianzch  app 的 context 上面挂载了 vue 上下文，你可以打印出来看看，你可以使用 this.app.vue.renderPage 方式,  具体请看：https://github.com/hubcarl/egg-view-vue-ssr/blob/master/app/extend/application.js 和 https://github.com/hubcarl/egg-view-vue-ssr/blob/master/lib/engine.js
